# docker-compose.yml
version: "3"
services:
  # 服务
  node:
    # node 服务
    build: . # Dockerfile 的目录，用于构建镜像
    # container_name: node-server-1 # 容器名称
    # ports: # 暴露的端口
    #    - "3000:3000"
    expose:
      - "3000"
    restart: always # 自动重启
    environment:
      - NODE_ENV=production
    networks:
      # 加入网络
      - "my-network"
    command: npm run start # 覆盖容器启动后默认执行的命令
  nginx:
    image: nginx:latest #指定 nginx 镜像
    ports:
      # 将本机的 7000 端口映射到容器的 80 端口
      - "7000:80"
    container_name: nginx-node
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - "my-network"
    links:
      # 设置 node 服务别名，其实是设置/etc/hosts的域名解析
      - "node"
    depends_on:
      # 指定依赖于哪个服务
      - node
networks:
  # 网络
  my-network:
    # 网络名称
    driver: bridge
